APP_NAME: "mini-wallet"
APP_TZ: "Asia/Jakarta"
JWT_SECRET: "6dNGvLj2fqsfXZqO2anRgKipR2pg9rmcxvvZ1BV59saaVqSQ3cngkGXRmCtMAF19"

APP_DB_HOST: "127.0.0.1"
APP_DB_PORT: "5432"
APP_DB_USERNAME: "postgres"
APP_DB_PASSWORD: "postgres"
APP_DB_NAME: "mini-wallet"
APP_DB_SSL: "disable"

